const db = require('../models');

const { PatientAccessLog } = db;

// Records that someone opened a patient's clinical record.
//
// Paired with the clinical.view gate on the same routes, so the question "who
// may look" and the record of "who did look" live one line apart and cannot
// drift. Adding a new clinical read means adding both or neither.
//
// Usage:
//   router.get('/', authenticate, authorize(...READ), logPatientAccess('consultation-notes'), ctrl.list)
//
// THREE THINGS THIS DELIBERATELY DOES NOT DO
//
// It does not block. The log is written after the handler has been allowed to
// proceed, and a failure to write is swallowed. An audit log that can take the
// clinic offline is a worse problem than a missing row — this is the same
// fire-and-forget shape as the existing login log.
//
// It does not log a patient reading their own record. Every patient opens their
// own file constantly; recording it would bury the entries that matter under
// noise generated by the person the log exists to protect.
//
// It exempts nobody else. The administrator account in particular is logged
// like everyone else — it holds every capability implicitly, which makes it the
// account most worth recording, not the one to excuse.
const logPatientAccess = (section) => (req, res, next) => {
  // Let the request continue immediately — nothing below is on the critical
  // path, and the log must never be able to delay or fail a clinical read.
  next();

  try {
    const user = req.user;
    const patient = req.patient;
    if (!user) return;

    // A patient opening their own file is not an access worth recording.
    if (user.role === 'patient') return;

    // Resolve the patient from whichever shape the route provides. findPatient
    // populates req.patient; the collection routes (consultation notes, GLP-1)
    // are filtered by a query parameter instead and have no req.patient, so the
    // uhid is taken from the query and the id left null rather than guessed.
    const patientId = patient?.id ?? null;
    const uhid = patient?.uhid ?? req.query?.uhid ?? req.params?.uhid ?? null;

    // Nothing identifying the patient means nothing worth writing: a row with
    // no subject cannot answer the only question this table exists to answer.
    if (patientId === null && !uhid) return;

    // The JWT payload carries `name` already assembled at login (see
    // authController) — req.user has no firstName/lastName to join. Reading
    // those would have written null into every single row.
    const name = user.name || null;

    // Not awaited. Failures are swallowed below rather than surfaced, because
    // by this point the response is already on its way to the client.
    PatientAccessLog.create({
      patientId,                    // null when the route resolves by uhid alone
      uhid,
      userId: user.id,
      userName: name,
      userRole: user.role,
      section,
      method: req.method,
      path: (req.originalUrl || '').split('?')[0].slice(0, 512),
      ipAddress: req.ip || req.headers['x-forwarded-for'] || null,
    }).catch(() => { /* fire and forget — see the note above */ });
  } catch {
    /* never let logging break a clinical read */
  }
};

module.exports = logPatientAccess;
